# Generated by Django 5.0.6 on 2024-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="authenapp/profile_pics"),
        ),
    ]
